spring.application.name=loans-service
spring.profiles.active=prod

server.port=8090
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8071}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/

eureka.instance.prefer-ip-address=true

info.app.name=loans
info.app.description=loans application
info.app.version=1.0.0

management.info.env.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=unrestricted
